<a href="https://colab.research.google.com/github/Nawaf9997/Traffic_Anlysis/blob/main/Task_1_Week_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tasks

## 1.Data Merging and cleaning

### Merge the two dataframes

In [10]:
import pandas as pd
df = pd.read_csv('/content/Dataset 1.csv')
df1 = pd.read_csv('/content/Dataset 2.csv')

<ipython-input-10-c36eebf6c7f0>:2: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/Dataset 1.csv')

In [11]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [12]:
df.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,3,17:42,12,E09000020,3,3218,6,30,0,-1,-1,0,0,1,1,2,2,0,0,1,1,E01002849
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,4,17:36,12,E09000020,4,450,3,30,6,2,5,0,0,5,4,1,1,0,0,1,1,E01002909
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,5,00:15,12,E09000020,5,0,6,30,0,-1,-1,0,0,0,4,1,1,0,0,1,1,E01002857
3,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,6,10:35,12,E09000020,3,3220,6,30,0,-1,-1,0,0,0,1,1,1,0,0,1,1,E01002840
4,200501BS00005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,2,21:13,12,E09000020,6,0,6,30,0,-1,-1,0,0,0,7,1,2,0,0,1,1,E01002863

In [13]:
df1.head()

,Accident_Index,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type
0,200501BS00001,1,1,3,1,37,7,2,1,1,0,0,-1,0,1
1,200501BS00002,1,1,2,1,37,7,3,0,0,0,4,-1,11,1
2,200501BS00003,2,1,1,1,62,9,3,0,0,0,0,-1,9,1
3,200501BS00004,1,1,3,1,30,6,3,5,2,0,0,-1,0,1
4,200501BS00005,1,1,1,1,49,8,3,0,0,0,0,-1,3,-1

In [14]:
df.columns

Index(['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR',
       'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity',
       'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week',
       'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)',
       '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit',
       'Junction_Detail', 'Junction_Control', '2nd_Road_Class',
       '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Conditions_at_Site', 'Carriageway_Hazards',
       'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'LSOA_of_Accident_Location'],
      dtype='object')

In [15]:
df1.columns

Index(['Accident_Index', 'Vehicle_Reference', 'Casualty_Reference',
       'Casualty_Class', 'Sex_of_Casualty', 'Age_of_Casualty',
       'Age_Band_of_Casualty', 'Casualty_Severity', 'Pedestrian_Location',
       'Pedestrian_Movement', 'Car_Passenger', 'Bus_or_Coach_Passenger',
       'Pedestrian_Road_Maintenance_Worker', 'Casualty_Type',
       'Casualty_Home_Area_Type'],
      dtype='object')

In [16]:
dfmrgd = pd.merge(df, df1,on="Accident_Index" ,how='inner')

In [17]:
dfmrgd.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,3,17:42,12,E09000020,3,3218,6,30,0,-1,-1,0,0,1,1,2,2,0,0,1,1,E01002849,1,1,3,1,37,7,2,1,1,0,0,-1,0,1
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,4,17:36,12,E09000020,4,450,3,30,6,2,5,0,0,5,4,1,1,0,0,1,1,E01002909,1,1,2,1,37,7,3,0,0,0,4,-1,11,1
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,5,00:15,12,E09000020,5,0,6,30,0,-1,-1,0,0,0,4,1,1,0,0,1,1,E01002857,2,1,1,1,62,9,3,0,0,0,0,-1,9,1
3,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,6,10:35,12,E09000020,3,3220,6,30,0,-1,-1,0,0,0,1,1,1,0,0,1,1,E01002840,1,1,3,1,30,6,3,5,2,0,0,-1,0,1
4,200501BS00005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,2,21:13,12,E09000020,6,0,6,30,0,-1,-1,0,0,0,7,1,2,0,0,1,1,E01002863,1,1,1,1,49,8,3,0,0,0,0,-1,3,-1

In [18]:
dfmrgd.columns

Index(['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR',
       'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity',
       'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week',
       'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)',
       '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit',
       'Junction_Detail', 'Junction_Control', '2nd_Road_Class',
       '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Conditions_at_Site', 'Carriageway_Hazards',
       'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'LSOA_of_Accident_Location', 'Vehicle_Reference', 'Casualty_Reference',
       'Casualty_Class', 'Sex_of_Casualty', 'Age_of_Casualty',
       'Age_Band_of_Casualty', 'Casualty_Severity', 'Pedestrian_Location',
       'Pedestrian_Movement', 'Car_Passenger', 'Bus_or_Coach_Passenger',
       'Pedestrian_Road_Maintenance_Worker', 'Casualty_Type',
       'Casualty_Home_Area_Type'],
      dtype='object')

In [19]:
dfmrgd.shape

(2216720, 46)

In [20]:
dfmrgd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2216720 entries, 0 to 2216719
Data columns (total 46 columns):
 #   Column                                       Dtype
---  ------                                       -----
 0   Accident_Index                               object
 1   Location_Easting_OSGR                        float64
 2   Location_Northing_OSGR                       float64
 3   Longitude                                    float64
 4   Latitude                                     float64
 5   Police_Force                                 int64
 6   Accident_Severity                            int64
 7   Number_of_Vehicles                           int64
 8   Number_of_Casualties                         int64
 9   Date                                         object
 10  Day_of_Week                                  int64
 11  Time                                         object
 12  Local_Authority_(District)                   int64
 13  Local_Authority_(Highway)                    object
 14  1st_Road_Class                               int64
 15  1st_Road_Number                              int64
 16  Road_Type                                    int64
 17  Speed_limit                                  int64
 18  Junction_Detail                              int64
 19  Junction_Control                             int64
 20  2nd_Road_Class                               int64
 21  2nd_Road_Number                              int64
 22  Pedestrian_Crossing-Human_Control            int64
 23  Pedestrian_Crossing-Physical_Facilities      int64
 24  Light_Conditions                             int64
 25  Weather_Conditions                           int64
 26  Road_Surface_Conditions                      int64
 27  Special_Conditions_at_Site                   int64
 28  Carriageway_Hazards                          int64
 29  Urban_or_Rural_Area                          int64
 30  Did_Police_Officer_Attend_Scene_of_Accident  int64
 31  LSOA_of_Accident_Location                    object
 32  Vehicle_Reference                            int64
 33  Casualty_Reference                           int64
 34  Casualty_Class                               int64
 35  Sex_of_Casualty                              int64
 36  Age_of_Casualty                              int64
 37  Age_Band_of_Casualty                         int64
 38  Casualty_Severity                            int64
 39  Pedestrian_Location                          int64
 40  Pedestrian_Movement                          int64
 41  Car_Passenger                                int64
 42  Bus_or_Coach_Passenger                       int64
 43  Pedestrian_Road_Maintenance_Worker           int64
 44  Casualty_Type                                int64
 45  Casualty_Home_Area_Type                      int64
dtypes: float64(4), int64(37), object(5)
memory usage: 778.0+ MB

In [21]:
import pandas as pd
df = pd.read_csv('/content/Dataset 1.csv')
df1 = pd.read_csv('/content/Dataset 2.csv')

<ipython-input-21-c36eebf6c7f0>:2: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/Dataset 1.csv')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1640597 entries, 0 to 1640596
Data columns (total 32 columns):
 #   Column                                       Non-Null Count    Dtype
---  ------                                       --------------    -----
 0   Accident_Index                               1640597 non-null  object
 1   Location_Easting_OSGR                        1640486 non-null  float64
 2   Location_Northing_OSGR                       1640486 non-null  float64
 3   Longitude                                    1640486 non-null  float64
 4   Latitude                                     1640486 non-null  float64
 5   Police_Force                                 1640597 non-null  int64
 6   Accident_Severity                            1640597 non-null  int64
 7   Number_of_Vehicles                           1640597 non-null  int64
 8   Number_of_Casualties                         1640597 non-null  int64
 9   Date                                         1640597 non-null  object
 10  Day_of_Week                                  1640597 non-null  int64
 11  Time                                         1640464 non-null  object
 12  Local_Authority_(District)                   1640597 non-null  int64
 13  Local_Authority_(Highway)                    1640597 non-null  object
 14  1st_Road_Class                               1640597 non-null  int64
 15  1st_Road_Number                              1640597 non-null  int64
 16  Road_Type                                    1640597 non-null  int64
 17  Speed_limit                                  1640597 non-null  int64
 18  Junction_Detail                              1640597 non-null  int64
 19  Junction_Control                             1640597 non-null  int64
 20  2nd_Road_Class                               1640597 non-null  int64
 21  2nd_Road_Number                              1640597 non-null  int64
 22  Pedestrian_Crossing-Human_Control            1640597 non-null  int64
 23  Pedestrian_Crossing-Physical_Facilities      1640597 non-null  int64
 24  Light_Conditions                             1640597 non-null  int64
 25  Weather_Conditions                           1640597 non-null  int64
 26  Road_Surface_Conditions                      1640597 non-null  int64
 27  Special_Conditions_at_Site                   1640597 non-null  int64
 28  Carriageway_Hazards                          1640597 non-null  int64
 29  Urban_or_Rural_Area                          1640597 non-null  int64
 30  Did_Police_Officer_Attend_Scene_of_Accident  1640597 non-null  int64
 31  LSOA_of_Accident_Location                    1520023 non-null  object
dtypes: float64(4), int64(23), object(5)
memory usage: 400.5+ MB

In [23]:
df.isna().sum()

Accident_Index                                      0
Location_Easting_OSGR                             111
Location_Northing_OSGR                            111
Longitude                                         111
Latitude                                          111
Police_Force                                        0
Accident_Severity                                   0
Number_of_Vehicles                                  0
Number_of_Casualties                                0
Date                                                0
Day_of_Week                                         0
Time                                              133
Local_Authority_(District)                          0
Local_Authority_(Highway)                           0
1st_Road_Class                                      0
1st_Road_Number                                     0
Road_Type                                           0
Speed_limit                                         0
Junction_Detail                                     0
Junction_Control                                    0
2nd_Road_Class                                      0
2nd_Road_Number                                     0
Pedestrian_Crossing-Human_Control                   0
Pedestrian_Crossing-Physical_Facilities             0
Light_Conditions                                    0
Weather_Conditions                                  0
Road_Surface_Conditions                             0
Special_Conditions_at_Site                          0
Carriageway_Hazards                                 0
Urban_or_Rural_Area                                 0
Did_Police_Officer_Attend_Scene_of_Accident         0
LSOA_of_Accident_Location                      120574
dtype: int64

In [24]:
df["Location_Easting_OSGR"].mode()

0    533650.0
Name: Location_Easting_OSGR, dtype: float64

In [25]:
df["Location_Easting_OSGR"].fillna("533650.0",inplace=True)

<ipython-input-25-dd32170e2004>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '533650.0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df["Location_Easting_OSGR"].fillna("533650.0",inplace=True)

In [26]:
df['Location_Northing_OSGR'].mode()

0    181310.0
Name: Location_Northing_OSGR, dtype: float64

In [27]:
df["Location_Northing_OSGR"].fillna("181310.0",inplace=True)

<ipython-input-27-f9586cffefe6>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '181310.0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df["Location_Northing_OSGR"].fillna("181310.0",inplace=True)

In [28]:
df["Longitude"].mode()

0   -0.977611
Name: Longitude, dtype: float64

In [29]:
df["Longitude"].fillna("-0.977611",inplace=True)

<ipython-input-29-263823216fc2>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '-0.977611' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df["Longitude"].fillna("-0.977611",inplace=True)

In [30]:
df["Latitude"].mode()

0    52.458798
Name: Latitude, dtype: float64

In [31]:
df["Latitude"].fillna("52.458798",inplace=True)

<ipython-input-31-a4b7e15d16a9>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '52.458798' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df["Latitude"].fillna("52.458798",inplace=True)

In [32]:
df["Time"].mode()

0    17:00
Name: Time, dtype: object

In [33]:
df["Time"].fillna("17:00",inplace=True)

In [34]:
df["LSOA_of_Accident_Location"].mode()

0    E01000004
Name: LSOA_of_Accident_Location, dtype: object

In [35]:
df["LSOA_of_Accident_Location"].fillna("E01000004",inplace=True)

In [36]:
df.isna().sum()

Accident_Index                                 0
Location_Easting_OSGR                          0
Location_Northing_OSGR                         0
Longitude                                      0
Latitude                                       0
Police_Force                                   0
Accident_Severity                              0
Number_of_Vehicles                             0
Number_of_Casualties                           0
Date                                           0
Day_of_Week                                    0
Time                                           0
Local_Authority_(District)                     0
Local_Authority_(Highway)                      0
1st_Road_Class                                 0
1st_Road_Number                                0
Road_Type                                      0
Speed_limit                                    0
Junction_Detail                                0
Junction_Control                               0
2nd_Road_Class                                 0
2nd_Road_Number                                0
Pedestrian_Crossing-Human_Control              0
Pedestrian_Crossing-Physical_Facilities        0
Light_Conditions                               0
Weather_Conditions                             0
Road_Surface_Conditions                        0
Special_Conditions_at_Site                     0
Carriageway_Hazards                            0
Urban_or_Rural_Area                            0
Did_Police_Officer_Attend_Scene_of_Accident    0
LSOA_of_Accident_Location                      0
dtype: int64

In [37]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2216720 entries, 0 to 2216719
Data columns (total 15 columns):
 #   Column                              Dtype
---  ------                              -----
 0   Accident_Index                      object
 1   Vehicle_Reference                   int64
 2   Casualty_Reference                  int64
 3   Casualty_Class                      int64
 4   Sex_of_Casualty                     int64
 5   Age_of_Casualty                     int64
 6   Age_Band_of_Casualty                int64
 7   Casualty_Severity                   int64
 8   Pedestrian_Location                 int64
 9   Pedestrian_Movement                 int64
 10  Car_Passenger                       int64
 11  Bus_or_Coach_Passenger              int64
 12  Pedestrian_Road_Maintenance_Worker  int64
 13  Casualty_Type                       int64
 14  Casualty_Home_Area_Type             int64
dtypes: int64(14), object(1)
memory usage: 253.7+ MB

In [38]:
df1.isna().sum()

Accident_Index                        0
Vehicle_Reference                     0
Casualty_Reference                    0
Casualty_Class                        0
Sex_of_Casualty                       0
Age_of_Casualty                       0
Age_Band_of_Casualty                  0
Casualty_Severity                     0
Pedestrian_Location                   0
Pedestrian_Movement                   0
Car_Passenger                         0
Bus_or_Coach_Passenger                0
Pedestrian_Road_Maintenance_Worker    0
Casualty_Type                         0
Casualty_Home_Area_Type               0
dtype: int64

In [39]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [40]:
dfmrgd = pd.merge(df, df1,on="Accident_Index" ,how='inner')

In [41]:
dfmrgd.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type
0,200501BS00001,525680.0,178240.0,-0.19117,51.489096,1,2,1,1,04/01/2005,3,17:42,12,E09000020,3,3218,6,30,0,-1,-1,0,0,1,1,2,2,0,0,1,1,E01002849,1,1,3,1,37,7,2,1,1,0,0,-1,0,1
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,4,17:36,12,E09000020,4,450,3,30,6,2,5,0,0,5,4,1,1,0,0,1,1,E01002909,1,1,2,1,37,7,3,0,0,0,4,-1,11,1
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,5,00:15,12,E09000020,5,0,6,30,0,-1,-1,0,0,0,4,1,1,0,0,1,1,E01002857,2,1,1,1,62,9,3,0,0,0,0,-1,9,1
3,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,6,10:35,12,E09000020,3,3220,6,30,0,-1,-1,0,0,0,1,1,1,0,0,1,1,E01002840,1,1,3,1,30,6,3,5,2,0,0,-1,0,1
4,200501BS00005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,2,21:13,12,E09000020,6,0,6,30,0,-1,-1,0,0,0,7,1,2,0,0,1,1,E01002863,1,1,1,1,49,8,3,0,0,0,0,-1,3,-1

## 2. Exploratory Data Analysis:

### Perform summary statistics on the dataset.

In [42]:
dfmrgd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2216720 entries, 0 to 2216719
Data columns (total 46 columns):
 #   Column                                       Dtype
---  ------                                       -----
 0   Accident_Index                               object
 1   Location_Easting_OSGR                        object
 2   Location_Northing_OSGR                       object
 3   Longitude                                    object
 4   Latitude                                     object
 5   Police_Force                                 int64
 6   Accident_Severity                            int64
 7   Number_of_Vehicles                           int64
 8   Number_of_Casualties                         int64
 9   Date                                         object
 10  Day_of_Week                                  int64
 11  Time                                         object
 12  Local_Authority_(District)                   int64
 13  Local_Authority_(Highway)                    object
 14  1st_Road_Class                               int64
 15  1st_Road_Number                              int64
 16  Road_Type                                    int64
 17  Speed_limit                                  int64
 18  Junction_Detail                              int64
 19  Junction_Control                             int64
 20  2nd_Road_Class                               int64
 21  2nd_Road_Number                              int64
 22  Pedestrian_Crossing-Human_Control            int64
 23  Pedestrian_Crossing-Physical_Facilities      int64
 24  Light_Conditions                             int64
 25  Weather_Conditions                           int64
 26  Road_Surface_Conditions                      int64
 27  Special_Conditions_at_Site                   int64
 28  Carriageway_Hazards                          int64
 29  Urban_or_Rural_Area                          int64
 30  Did_Police_Officer_Attend_Scene_of_Accident  int64
 31  LSOA_of_Accident_Location                    object
 32  Vehicle_Reference                            int64
 33  Casualty_Reference                           int64
 34  Casualty_Class                               int64
 35  Sex_of_Casualty                              int64
 36  Age_of_Casualty                              int64
 37  Age_Band_of_Casualty                         int64
 38  Casualty_Severity                            int64
 39  Pedestrian_Location                          int64
 40  Pedestrian_Movement                          int64
 41  Car_Passenger                                int64
 42  Bus_or_Coach_Passenger                       int64
 43  Pedestrian_Road_Maintenance_Worker           int64
 44  Casualty_Type                                int64
 45  Casualty_Home_Area_Type                      int64
dtypes: int64(37), object(9)
memory usage: 778.0+ MB

In [43]:
dfmrgd.sample(10)

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type
917862,2008400D02278,493690.0,240590.0,-0.634971,52.055742,40,3,2,2,31/07/2008,5,10:39,422,E06000056,5,70,6,60,3,4,5,70,0,0,1,1,1,0,0,2,1,E01017396,2,2,1,1,33,6,3,0,0,0,0,-1,9,1
1821081,2012620214578,274150.0,194580.0,-3.819947,51.635862,62,3,2,2,14/01/2012,7,13:30,743,W06000012,6,0,6,30,9,4,6,0,0,0,1,1,1,0,0,1,1,W01000895,1,2,2,2,13,3,3,0,0,1,0,0,9,-1
2127020,2014331400344,469420.0,293425.0,-0.978001,52.534244,33,3,2,1,19/02/2014,4,17:42,363,E10000018,3,6,6,50,3,4,5,6401,0,0,4,1,2,0,0,2,1,E01025784,2,1,1,1,53,8,3,0,0,0,0,0,9,1
225350,2005520026484,359580.0,174480.0,-2.583308,51.467785,52,3,1,1,24/02/2005,5,08:50,601,E06000023,6,0,6,30,0,-1,-1,0,0,0,1,8,2,0,0,1,2,E01014488,1,1,3,2,7,2,3,6,9,0,0,-1,0,1
1072003,2009120018070,504140.0,487350.0,-0.402315,54.271211,12,3,2,1,21/01/2009,4,13:40,186,E10000023,3,165,6,30,2,4,6,0,0,8,1,1,1,0,0,1,2,E01027868,1,1,2,2,47,8,3,0,0,1,0,-1,9,1
2138514,201437EA84049,610573.0,239392.0,1.067104,52.01294,37,3,3,2,26/09/2014,6,19:40,410,E10000029,3,12,3,70,9,4,5,495,0,0,4,1,1,0,0,2,1,E01029877,3,2,1,1,42,7,3,0,0,0,0,0,9,1
510593,200663BC09406,237910.0,246290.0,-4.367466,52.091119,63,3,3,2,23/06/2006,6,08:29,750,W06000008,3,486,6,60,3,4,6,0,0,0,1,1,1,0,0,2,1,W01000551,1,2,2,2,31,6,3,0,0,1,0,-1,9,1
1494014,2011100381211,417420.0,561320.0,-1.72957,54.946257,10,3,2,2,06/07/2011,4,07:45,146,E08000020,6,3018,3,30,3,4,6,3017,0,0,1,8,2,0,0,2,1,E01008276,2,2,1,1,41,7,3,0,0,0,0,0,9,-1
1328178,201022F002283,341210.0,317010.0,-2.872396,52.747474,22,3,2,2,02/05/2010,1,19:50,286,E06000051,3,5,6,60,3,4,6,0,0,0,1,1,1,0,0,2,1,E01028969,2,2,1,2,46,8,3,0,0,0,0,-1,9,2
869601,200820E134601,401210.0,279180.0,-1.983649,52.41059,20,3,1,1,30/09/2008,3,08:09,300,E08000025,6,0,6,30,3,4,6,0,0,0,1,2,2,0,0,1,1,E01009207,1,1,3,2,11,3,3,5,4,0,0,-1,0,1

### Identify and analyze patterns in the data.

In [44]:
dfmrgd.describe()

,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Day_of_Week,Local_Authority_(District),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type
count,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06,2.216720e+06
mean,3.091263e+01,2.817538e+00,1.934206e+00,1.856240e+00,4.115620e+00,3.561148e+02,4.017567e+00,1.018388e+03,5.155387e+00,4.030029e+01,2.334406e+00,1.768504e+00,2.601299e+00,3.808535e+02,8.821592e-03,6.981834e-01,1.988344e+00,1.576465e+00,1.374416e+00,1.154142e-01,7.423761e-02,1.391237e+00,1.167156e+00,1.485031e+00,1.433611e+00,1.493615e+00,1.416186e+00,3.435309e+01,6.020044e+00,2.866671e+00,6.663922e-01,4.740599e-01,2.828526e-01,9.074669e-02,-6.254159e-01,7.510757e+00,9.904936e-01
std,2.522360e+01,4.308973e-01,9.010872e-01,2.044728e+00,1.954008e+00,2.561145e+02,1.435446e+00,1.829295e+03,1.631020e+00,1.470085e+01,2.594839e+00,2.307629e+00,3.214759e+00,1.303353e+03,1.239422e-01,1.781750e+00,1.681440e+00,1.629088e+00,6.322214e-01,7.487071e-01,6.254824e-01,4.882038e-01,3.789881e-01,6.671878e-01,1.404250e+00,7.062961e-01,4.946520e-01,1.885804e+01,2.406346e+00,3.692819e-01,1.959742e+00,1.660281e+00,5.933772e-01,5.674798e-01,5.526900e-01,7.170375e+00,1.031795e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+00,1.000000e+00,1.000000e+01,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,1.000000e+00,-1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00,-1.000000e+00
25%,7.000000e+00,3.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.290000e+02,3.000000e+00,0.000000e+00,6.000000e+00,3.000000e+01,0.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+01,4.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00,3.000000e+00,1.000000e+00
50%,3.100000e+01,3.000000e+00,2.000000e+00,1.000000e+00,4.000000e+00,3.280000e+02,3.000000e+00,1.350000e+02,6.000000e+00,3.000000e+01,2.000000e+00,2.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.100000e+01,6.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00,9.000000e+00,1.000000e+00
75%,4.600000e+01,3.000000e+00,2.000000e+00,2.000000e+00,6.000000e+00,5.320000e+02,6.000000e+00,7.250000e+02,6.000000e+00,6.000000e+01,3.000000e+00,4.000000e+00,6.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,1.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,4.600000e+01,8.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00,1.000000e+00
max,9.800000e+01,3.000000e+00,6.700000e+01,9.300000e+01,7.000000e+00,9.410000e+02,6.000000e+00,9.999000e+03,9.000000e+00,7.000000e+01,9.000000e+00,4.000000e+00,6.000000e+00,9.999000e+03,2.000000e+00,8.000000e+00,7.000000e+00,9.000000e+00,5.000000e+00,7.000000e+00,7.000000e+00,3.000000e+00,3.000000e+00,9.100000e+01,8.520000e+02,3.000000e+00,2.000000e+00,1.030000e+02,1.100000e+01,3.000000e+00,1.000000e+01,9.000000e+00,2.000000e+00,4.000000e+00,2.000000e+00,9.800000e+01,3.000000e+00

In [45]:
dfmrgd = dfmrgd.drop(columns=[
    'Location_Easting_OSGR', 'Location_Northing_OSGR', 'Longitude', 'Latitude',
    'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities',
    'Bus_or_Coach_Passenger', 'Pedestrian_Road_Maintenance_Worker'
], errors='ignore')

In [46]:
print(dfmrgd.columns)

Index(['Accident_Index', 'Police_Force', 'Accident_Severity',
       'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week',
       'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)',
       '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit',
       'Junction_Detail', 'Junction_Control', '2nd_Road_Class',
       '2nd_Road_Number', 'Light_Conditions', 'Weather_Conditions',
       'Road_Surface_Conditions', 'Special_Conditions_at_Site',
       'Carriageway_Hazards', 'Urban_or_Rural_Area',
       'Did_Police_Officer_Attend_Scene_of_Accident',
       'LSOA_of_Accident_Location', 'Vehicle_Reference', 'Casualty_Reference',
       'Casualty_Class', 'Sex_of_Casualty', 'Age_of_Casualty',
       'Age_Band_of_Casualty', 'Casualty_Severity', 'Pedestrian_Location',
       'Pedestrian_Movement', 'Car_Passenger', 'Casualty_Type',
       'Casualty_Home_Area_Type'],
      dtype='object')

In [47]:
dfmrgd.tail()

,Accident_Index,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Casualty_Type,Casualty_Home_Area_Type
2216715,2014984137714,98,3,1,1,09/12/2014,3,02:00,917,S12000006,4,721,6,40,0,-1,-1,0,4,1,4,0,0,2,1,E01000004,1,1,2,2,16,4,3,0,0,2,9,1
2216716,2014984138414,98,2,3,2,17/12/2014,4,06:55,917,S12000006,3,75,6,60,3,4,5,43,6,2,2,0,0,2,1,E01000004,1,1,1,1,27,6,3,0,0,0,9,1
2216717,2014984138414,98,2,3,2,17/12/2014,4,06:55,917,S12000006,3,75,6,60,3,4,5,43,6,2,2,0,0,2,1,E01000004,2,2,1,1,44,7,2,0,0,0,19,1
2216718,2014984139614,98,3,2,2,24/12/2014,4,15:00,917,S12000006,4,723,6,60,3,4,4,7076,1,1,2,0,0,2,1,E01000004,1,2,2,1,61,9,3,0,0,0,11,2
2216719,2014984139614,98,3,2,2,24/12/2014,4,15:00,917,S12000006,4,723,6,60,3,4,4,7076,1,1,2,0,0,2,1,E01000004,2,1,1,1,79,11,3,0,0,0,9,3

In [48]:
dfmrgd['Sex_of_Casualty']  = dfmrgd['Sex_of_Casualty'] .apply(str)

In [49]:
dfmrgd['Sex_of_Casualty'] = dfmrgd['Sex_of_Casualty'].apply(lambda x: str(x).replace( "1" , 'male'))
dfmrgd['Sex_of_Casualty'] = dfmrgd['Sex_of_Casualty'].apply(lambda x: str(x).replace( "2" , 'female'))

In [50]:
dfmrgd.head()

,Accident_Index,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Casualty_Type,Casualty_Home_Area_Type
0,200501BS00001,1,2,1,1,04/01/2005,3,17:42,12,E09000020,3,3218,6,30,0,-1,-1,0,1,2,2,0,0,1,1,E01002849,1,1,3,male,37,7,2,1,1,0,0,1
1,200501BS00002,1,3,1,1,05/01/2005,4,17:36,12,E09000020,4,450,3,30,6,2,5,0,4,1,1,0,0,1,1,E01002909,1,1,2,male,37,7,3,0,0,0,11,1
2,200501BS00003,1,3,2,1,06/01/2005,5,00:15,12,E09000020,5,0,6,30,0,-1,-1,0,4,1,1,0,0,1,1,E01002857,2,1,1,male,62,9,3,0,0,0,9,1
3,200501BS00004,1,3,1,1,07/01/2005,6,10:35,12,E09000020,3,3220,6,30,0,-1,-1,0,1,1,1,0,0,1,1,E01002840,1,1,3,male,30,6,3,5,2,0,0,1
4,200501BS00005,1,3,1,1,10/01/2005,2,21:13,12,E09000020,6,0,6,30,0,-1,-1,0,7,1,2,0,0,1,1,E01002863,1,1,1,male,49,8,3,0,0,0,3,-1

In [51]:
dfmrgd.sample(10)

,Accident_Index,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Casualty_Type,Casualty_Home_Area_Type
435652,200642I325708,42,3,2,1,16/08/2006,4,15:57,459,E10000012,6,0,6,30,3,4,6,0,1,1,1,0,0,1,1,E01021965,1,1,1,female,17,4,3,0,0,0,9,1
1270031,201005DD05906,5,3,1,1,16/10/2010,7,12:35,92,E08000013,6,0,6,30,9,4,6,0,1,1,1,0,0,1,1,E01006832,1,1,3,female,51,8,3,5,1,0,0,1
1510609,201114B040311,14,3,2,2,03/05/2011,3,17:15,210,E08000016,3,61,6,30,3,4,6,0,1,1,1,0,0,1,2,E01007338,1,2,2,female,15,3,3,0,0,2,9,1
2039356,201401QA10386,1,3,1,1,18/08/2014,2,12:40,29,E09000015,4,458,6,30,9,2,5,0,1,1,1,0,0,1,1,E01002129,1,1,2,female,85,11,3,0,0,0,11,1
1472784,201104CM11053,4,3,3,2,21/04/2011,5,23:00,83,E10000017,3,582,1,60,1,4,6,0,4,1,1,0,0,2,1,E01025429,2,1,1,male,18,4,3,0,0,0,9,-1
1317244,201020M005100,20,3,2,3,04/07/2010,1,10:16,302,E08000026,3,4114,6,30,3,4,6,0,1,1,1,0,0,1,1,E01009643,2,1,1,female,58,9,3,0,0,0,9,1
909705,2008350420908,35,3,1,1,08/11/2008,7,20:30,391,E10000003,6,0,6,60,0,-1,-1,0,6,1,1,0,7,2,2,E01018035,1,1,1,male,40,7,3,0,0,0,9,3
251476,200563AC59905,63,3,2,1,29/11/2005,3,12:05,751,W06000010,3,48,1,70,1,4,3,483,1,1,1,0,0,2,1,W01000699,1,1,1,male,40,7,3,0,0,0,5,3
233062,2005530183343,53,2,3,6,22/08/2005,2,08:50,621,E10000013,3,40,6,60,0,0,-1,0,1,2,2,5,0,2,1,E01022216,3,3,1,female,58,9,3,0,0,0,9,3
646911,2007230796791,23,2,2,3,14/10/2007,1,07:00,292,E10000031,1,6,3,70,0,-1,-1,0,1,1,1,0,0,2,1,E01031128,2,2,1,male,43,7,3,0,0,0,9,1

In [52]:
dfmrgd['Day_of_Week']  = dfmrgd['Day_of_Week'] .apply(str)

In [54]:
dfmrgd['Day_of_Week'] = dfmrgd['Day_of_Week'].apply(lambda x: str(x).replace( "1" , 'Sunday '))
dfmrgd['Day_of_Week'] = dfmrgd['Day_of_Week'].apply(lambda x: str(x).replace( "2" , 'Monday '))
dfmrgd['Day_of_Week'] = dfmrgd['Day_of_Week'].apply(lambda x: str(x).replace( "3" , 'Tuesday'))
dfmrgd['Day_of_Week'] = dfmrgd['Day_of_Week'].apply(lambda x: str(x).replace( "4" , 'Wednesday'))
dfmrgd['Day_of_Week'] = dfmrgd['Day_of_Week'].apply(lambda x: str(x).replace( "5" , 'Thursday'))
dfmrgd['Day_of_Week'] = dfmrgd['Day_of_Week'].apply(lambda x: str(x).replace( "6" , 'Friday'))
dfmrgd['Day_of_Week'] = dfmrgd['Day_of_Week'].apply(lambda x: str(x).replace( "7" , 'Saturday'))

In [55]:
dfmrgd.sample(10)

,Accident_Index,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Casualty_Type,Casualty_Home_Area_Type
1720301,201220G003952,20,3,3,1,11/04/2012,Wednesday,17:15,309,E08000031,3,454,3,30,6,2,6,0,1,8,1,0,0,1,1,E01010446,2,1,1,male,34,6,3,0,0,0,9,1
1489728,2011070206711,7,3,1,4,24/07/2011,Sunday,23:06,130,E06000050,1,6,3,70,0,-1,-1,0,6,1,1,0,0,2,1,E01018722,1,1,1,male,49,8,3,0,0,0,9,1
1253769,201001XD80030,1,3,2,4,22/01/2010,Friday,21:50,27,E09000009,3,40,6,30,0,-1,-1,0,4,1,1,0,0,1,1,E01001277,1,3,2,female,20,4,3,0,0,2,9,-1
1501594,2011130031207,13,3,2,3,20/01/2011,Thursday,16:50,204,E08000035,6,0,6,30,0,-1,-1,0,4,1,1,0,0,1,1,E01011690,2,2,1,male,39,7,3,0,0,0,9,1
1794065,2012460218029,46,3,2,1,04/09/2012,Tuesday,12:50,530,E10000016,1,20,3,70,0,-1,-1,0,1,1,1,0,0,2,1,E01023983,1,1,1,female,86,11,3,0,0,0,9,3
95019,200514C053705,14,2,2,2,06/04/2005,Wednesday,09:20,213,E08000018,4,6089,6,30,9,4,6,0,1,2,2,0,0,2,1,E01007731,1,1,1,male,29,6,3,0,0,0,9,1
313224,200605BB10519,5,3,2,1,17/05/2006,Wednesday,12:40,93,E08000014,3,567,6,30,3,4,6,0,1,1,2,0,0,1,1,E01007013,1,1,1,male,65,9,3,0,0,0,9,1
1797609,2012471201729,47,3,2,3,03/04/2012,Tuesday,17:09,559,E10000032,6,0,6,60,3,4,6,0,1,1,1,0,0,2,1,E01031513,2,2,2,female,31,6,3,0,0,1,9,2
913017,200836T080188,36,3,1,1,27/09/2008,Saturday,18:50,402,E10000020,6,0,6,30,0,-1,-1,0,5,1,1,0,0,1,2,E01026623,1,1,3,male,8,2,3,5,1,0,0,1
1450492,201101MM70541,1,3,2,1,25/07/2011,Monday,17:32,8,E09000028,3,201,6,30,8,4,4,240,1,1,1,0,0,1,1,E01003962,1,1,1,male,26,6,3,0,0,0,3,1

In [56]:
dfmrgd['Did_Police_Officer_Attend_Scene_of_Accident']  = dfmrgd['Did_Police_Officer_Attend_Scene_of_Accident'] .apply(str)

In [57]:
dfmrgd['Did_Police_Officer_Attend_Scene_of_Accident'] = dfmrgd['Did_Police_Officer_Attend_Scene_of_Accident'].apply(lambda x: str(x).replace( "1" , 'YES'))
dfmrgd['Did_Police_Officer_Attend_Scene_of_Accident'] = dfmrgd['Did_Police_Officer_Attend_Scene_of_Accident'].apply(lambda x: str(x).replace( "2" , 'NO'))

In [58]:
dfmrgd.sample(2)

,Accident_Index,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Casualty_Type,Casualty_Home_Area_Type
1391424,2010460190919,46,3,1,5,13/09/2010,Monday,14:55,533,E10000016,3,256,3,70,1,4,6,0,1,1,1,0,0,2,YES,E01024256,1,4,2,female,16,4,3,0,0,2,9,1
465028,2006460124112,46,3,2,3,02/04/2006,Sunday,14:23,536,E10000016,4,2163,6,60,0,-1,-1,0,1,1,1,0,0,2,YES,E01024410,1,1,1,male,71,10,3,0,0,0,9,2

In [59]:
dfmrgd.duplicated().sum()

0

In [60]:
dfmrgd = dfmrgd.drop_duplicates()

In [62]:
from google.colab import files
dfmrgd.to_csv('dfmrgd.csv', encoding = 'utf-8-sig')
files.download('dfmrgd.csv')

## 3. Data visualization

### Create visualizations to illustrate the findings from the EDA.

In [73]:
# now we can do the heatmap :

sns.heatmap(dfmrgd , annot= True)
plt.title("how parent's Education effect on student's score")
plt.show()

ValueError: could not convert string to float: '200501BS00001'

### Use appropriate plots such as histograms, bar charts, pie charts, scatter plots, and heatmaps.

## 4. Applying Machine Learning Model

*   List item
*   List item

In [67]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('/content/dfmrgd.csv')

X = df.drop(columns=['Day_of_Week'])
y = df['Time']

<ipython-input-67-2fa0d73e334e>:5: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/dfmrgd.csv')

### Initialize your model

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### Train and Test your model

In [71]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('/content/dfmrgd.csv')

# Identify columns with object (string) dtype
object_cols = df.select_dtypes(include='object').columns

# Option 1: Drop non-numerical columns (if they are not relevant for your model)
X = df.drop(columns=['Day_of_Week'] + list(object_cols))

# Option 2: Encode categorical features (if they are relevant)
# You'll need to choose an appropriate encoding method (e.g., one-hot encoding, label encoding)
# Example using one-hot encoding:
# from sklearn.preprocessing import OneHotEncoder
# encoder = OneHotEncoder()
# encoded_data = encoder.fit_transform(df[object_cols])
# # ... integrate encoded data into your feature matrix X

y = df['Time']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

<ipython-input-71-4b6bd25be5fb>:5: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/dfmrgd.csv')